config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    member do
      get :pjmembers
    end
  end
  
  resources :projects do
    resources :tasks
    member do
      get :pjmembers
    end
  end
  
  resource :pjmembers, only: [:create, :destroy]
  resource :assign_members, only: [:create, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  
  has_many :assign_members, dependent: :destroy
  has_many :task_menbers, through: :assign_members, source: :user, dependent: :destroy
  
  validates :title, presence: true, length: {maximum: 10}
  validates :priority, presence: true
  validates :schedule, presence: true
  validates :progress, presence: true
  validates :alarm, presence: true
  validates :comment, presence: true
  
  def assign_member(user)
    self.assign_members.find_or_create_by(user_id: user.id)
  end
  
  def assignout(user)
    assign_member = self.assign_members.find_by(user_id: user.id)
    assign_member.destroy if assign_member
  end
  
  def assign_member?(user)
    self.assign_member_tasks.include?(user)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @tasks = Task.all.page(params[:page])
  end
  
  def show
    @all_users = User.all.page(params[:page])
    @users = User.where.not(id: AssignMember.where(task_id: @task.id).pluck(:user_id))
    @taskmember = current_user.assign_members.build(task_id: @task.id)
    @taskmember_users = User.where(id: AssignMember.where(task_id: @task.id).pluck(:user_id))
  end
  
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end
  
  def create
    @project = Project.find(params[:project_id])
    @task = current_user.tasks.build(task_params)
    @task.project_id = @project.id
    
    if @task.save
      flash[:success] = 'タスクが正常に登録されました'
      redirect_to @project
    else
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'タスクが登録されませんでした'
      render :new
    end
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @task = current_user.tasks.find(params[:id])
    @task.project_id = @project.id
    @all_users = User.all.page(params[:page])
    @users = User.where.not(id: AssignMember.where(task_id: @task.id).pluck(:user_id))
    @taskmember = current_user.assign_members.build(task_id: @task.id)
    @taskmember_users = User.where(id: AssignMember.where(task_id: @task.id).pluck(:user_id))
  end
  
  def update
    @project = Project.find(params[:project_id])
    @task = current_user.tasks.find(params[:id])
    @task.project_id = @project.id
    
    if @task.update(task_params)
      flash[:success] = 'タスクが正常に更新されました'
      redirect_to project_path
    else
      flash.now[:danger] = 'タスクが更新されませんでした'
      render :new
    end
  end
  
  def destroy
    @project = Project.find(params[:project_id])
    @task = current_user.tasks.find_by(id: @task)
    @task.project_id = @project.id
    
    @task.destroy
    flash[:success] = 'タスクは正常に削除されました'
    redirect_to root_url
  end
  
  private

  def set_task
    @task = Task.find(params[:id])
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end

  def task_params
    params.require(:task).permit(:title, :priority, :schedule, :progress, :alarm, :comment)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_for(@task, url: project_tasks_path(@project)) do |f| %>
    <%= render 'layouts/error_messages', model: @task %> 
    <div class="form-group">
      <label>タスク名：</label>
      <%= f.text_area :title, class: 'form-control', rows: 1 %>
    </div>
    
    <div class="form-group">
      <%= f.label :priority, '優先度' %>
      <%= f.select :priority,[["緊急","緊急"],["普通","普通"]], class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <label>締切日：</label>
      <%= f.text_area :schedule, class: 'col-sx-9', rows: 1  %>(YYYYMMDD)
    </div>
    
    <div class="form-group">
      <label>進捗：</label>
      <%= f.text_area :progress, class:  'col-sx-2', rows: 1 %>％
    </div>

    <div class="form-group">
      <%= f.label :alarm, 'アラーム' %>
      <%= f.select :alarm,[["なし","なし"],["あり","あり"]], class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <label>コメント</label>
      <%= f.text_area :comment, class: 'form-control', rows: 6 %>
    </div>
    
    <div class="form-group">
      <labelメンバー：</label>
    </div>
    <%= f.submit 'タスクを登録する', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/_tasks.html.erb
<ul class="media-list">
　  <table class="table table-bordered">
      <tr>
        <th>タスク名</th>
        <th>優先度</th>
        <th>締切日</th>
        <th>進捗度</th>
        <th>アラーム</th>
      </tr>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, project_task_path(@project) %></td>
        <td><%= task.priority %></td>
        <td><%= task.schedule %></td>
        <td>
          <div class="progress">
　　　　　　<div class="progress-bar progress-bar-striped active" role="progressbar" style="width: <%= task.progress %>%;">
　　　　　　<%= task.progress %>％
　　　　　　</div>
　　　　　</div>
	　　　</td>
        <td><%= task.alarm %></td>
      </tr>
  <% end %>
  <%= paginate @tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1><%= @task.title %> タスク編集ページ</h1>

<div class="container">
  <%= form_for(@task, url: project_task_path(@project,@task)) do |f| %>
    <%= render 'layouts/error_messages', model: @task %> 
    <div class="form-group">
      <label>タスク名：</label>
      <%= f.text_area :title, class: 'form-control', rows: 1 %>
    </div>
    
    <div class="form-group">
      <%= f.label :priority, '優先度' %>
      <%= f.select :priority,[["緊急","緊急"],["普通","普通"]], class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <label>締切日：</label>
      <%= f.text_area :schedule, class: 'col-sx-9', rows: 1  %>(YYYYMMDD)
    </div>
    
    <div class="form-group">
      <label>進捗：</label>
      <%= f.text_area :progress, class:  'col-sx-2', rows: 1 %>％
    </div>

    <div class="form-group">
      <%= f.label :alarm, 'アラーム' %>
      <%= f.select :alarm,[["なし","なし"],["あり","あり"]], class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <label>コメント</label>
      <%= f.text_area :comment, class: 'form-control', rows: 6 %>
    </div>
    
    <div class="form-group">
      <label>担当者：</label>
          <% @taskmember_users.each do |taskmember_user| %>
            <%= taskmember_user.name %>
          <% end %>
    </div>
    <%= f.submit 'タスクを登録する', class: 'btn btn-primary' %>
  <% end %>
</div>
        <p>メンバーを追加する</p>
          <%= form_for(@taskmember) do |f| %>
            <%= f.hidden_field :task_id %>
            <%= f.collection_select :user_id, @users, :id, :name %>
            <%= f.submit "登録" %>
          <% end %>
        <br>
        <p>メンバーを削除する</p>
          <%= form_for(@taskmember, url: assign_members_path, html: { method: :delete }) do |f| %>
            <%= f.hidden_field :task_id %>
            <%= f.collection_select :user_id, @taskmember_users, :id, :name %>
            <%= f.submit "削除" %>
        <% end %>
        <br>

<div class="container">
  <%= link_to 'タスクを削除する', project_task_path(@project, @task), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>タスク新規作成</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %>タスク詳細</h1>
<div>
  <%= link_to 'このタスクを編集する', edit_project_task_path(@task), class: 'btn btn-warning pull-right' %>
</div>

<table class="table table-bordered">
  <tr>
    <th>タスク名</th>
    <td><%= @task.title %></td>
  </tr>
  <tr>
    <th>優先度</th>
    <td><%= @task.priority %></td>
  </tr>
  <tr>
    <th>締切</th>
    <td><%= @task.schedule %></td>
  </tr>
  <tr>
    <th>進捗</th>
    <td><%= @task.progress %></td>
  </tr>
  <tr>
    <th>アラーム</th>
    <td><%= @task.alarm %></td>
  </tr>
  <tr>
    <th>コメント</th>
    <td><%= @task.comment %></td>
  </tr>
  <tr>
    <th>担当者</th>
    <td>
      <% @taskmember_users.each do |taskmember_user| %>
        <%= taskmember_user.name %>
      <% end %>
    </td>
  </tr>
</table>