config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    member do
      get :pjmembers
    end
  end
  
  resources :projects do
    resources :tasks
    member do
      get :pjmembers
    end
  end
  
  resource :pjmembers, only: [:create, :destroy]
  resource :assign_members, only: [:create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :comment, presence: true
  validates :start_day, presence: true
  validates :end_day, presence: true
  
  belongs_to :user
  
  has_many :pjmembers, dependent: :destroy
  has_many :assign_users, through: :pjmembers, source: :user, dependent: :destroy
  
  has_many :tasks, dependent: :destroy
  
  def pjmember(user)
    self.pjmembers.find_or_create_by(user_id: user.id)
  end
  
  def pjout(user)
    pjmember = self.pjmembers.find_by(user_id: user.id)
    pjmember.destroy if pjmember
  end
  
  def pjmember?(user)
    self.pjmember_users.include?(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
 
  def index
    @projects = Project.all.page(params[:page])
  end
  
  def show
    @users = User.where.not(id: Pjmember.where(project_id: @project.id).pluck(:user_id))
    @pjmember = current_user.pjmembers.build(project_id: @project.id)
    @pjmember_users = User.where(id: Pjmember.where(project_id: @project.id).pluck(:user_id))
    @tasks = Task.all.page(params[:page])
    @task = @project.tasks.find_by(project: @task)
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = 'プロジェクトを作成しました。'
      redirect_to root_url
    else
      @projects = current_user.assign_projects.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'プロジェクトの作成に失敗しました。'
      render 'toppages/index'
    end
  end
  
  def edit
    @all_users = User.all.page(params[:page])
    @users = User.where.not(id: Pjmember.where(project_id: @project.id).pluck(:user_id))
    @pjmember = current_user.pjmembers.build(project_id: @project.id)
    @pjmember_users = User.where(id: Pjmember.where(project_id: @project.id).pluck(:user_id))
  end
  
  def update
    if @project.update(project_params)
      flash[:success] = 'プロジェクト情報が更新されました'
      redirect_to @project
    else
      flash.now[:danger] = 'プロジェクト情報は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:success] = 'プロジェクトを削除しました。'
    redirect_to root_url
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :comment, :start_day, :end_day)
  end

  def correct_user
    @project = current_user.projects.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% @pjmember = Pjmember.new unless @pjmember %>

<div class="container">
  <%= form_for(@project) do |f| %>
    <%= render 'layouts/error_messages', model: @project %> 
    <div class="form-group">
      <label>プロジェクト名：</label>
      <%= f.text_area :title, class: 'form-control', rows: 1 %>
    </div>
    <div class="form-group">
      <label>概要　：</label>
      <%= f.text_area :comment, class: 'form-control', rows: 5 %>
    </div>
    <div class="form-group">
      <label>開始日：</label>
      <%= f.text_area :start_day, class: 'col-sx-9', rows: 1 %>
      <label>終了日：</label>
      <%= f.text_area :end_day, class: 'col-sx-9', rows: 1 %>(YYYYMMDD)
    </div>

    <%= f.submit 'プロジェクトを登録する', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/projects/_ownprojects.html.erb
<ul class="media-list">
  <% @projects.each do |project| %>
    <li class="media">
      <div class="media-body">
        <div>
          <%= link_to project.user.name, user_path(project.user) %> <span class="text-muted">posted at <%= project.created_at %></span>
        </div>
        <div>
          <%= link_to project.title, project_path(project) %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @projects %>
</ul>

app/views/projects/_projects.html.erb
<ul class="media-list">
  <% projects.each do |project| %>
    <li class="media">
      <div class="media-body">
        <div>
          <%= link_to project.user.name, user_path(project.user) %> <span class="text-muted">posted at <%= project.created_at %></span>
        </div>
        <div>
          <%= link_to project.title, project_path(project) %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate projects %>
</ul>

app/views/projects/edit.html.erb
<h1><%= @project.title %> プロジェクト編集ページ</h1>

<%= render 'form', project: @project %>
<br>
<br>
<p>メンバーを追加する</p>
<%= form_for(@pjmember) do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.collection_select :user_id, @users, :id, :name %>
  <%= f.submit "登録" %>
<% end %>
<br>
<p>メンバーを削除する</p>
<%= form_for(@pjmember, url: pjmembers_path, html: { method: :delete }) do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.collection_select :user_id, @pjmember_users, :id, :name %>
  <%= f.submit "削除" %>
<% end %>
<br>
<p>参加メンバー</p>
<% @pjmember_users.each do |pjmember_user| %>
　<%= pjmember_user.name %>
<% end %>
<br>
<br>
<br>
<div class="container">
  <%= link_to 'プロジェクトを削除する', @project, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
</div>

app/views/projects/new.html.erb
<h1>プロジェクト新規作成</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %>プロジェクト詳細</h1>
<div>
  <%= link_to 'このプロジェクトを編集する', edit_project_path(@project), class: 'btn btn-warning pull-right' %>
</div>

<table class="table table-bordered">
  <tr>
    <th>プロジェクト名</th>
    <td><%= @project.title %></td>
  </tr>
  <tr>
    <th>概要</th>
    <td><%= @project.comment %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @project.start_day %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @project.end_day %></td>
  </tr>
  <tr>
    <th>メンバー</th>
    <td>
      <% @pjmember_users.each do |pjmember_user| %>
        <%= pjmember_user.name %>
      <% end %>
    </td>
</table>
<div>
  <%= link_to 'タスクの追加', new_project_task_path(@project, @task), class: 'btn btn-warning' %>
</div>
<br>
<div>
  <%= render 'tasks/tasks', tasks: @tasks %>
</div>